import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import Prvider from "@/redux/Prvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lamamia App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <Prvider>
            <Navbar />

            {children}

            <Footer />
          </Prvider>
        </div>
      </body>
    </html>
  );
}
